# PyScoutFM

## Getting Started

Firstly, there are two views supplied with the tool; one for the squad screen and one for the player search screen. Make sure both are imported into the game.

When in your selected screen, select all of the players (`ctrl + a` for Windows and `cmd + a` for Mac) before exporting them (`ctrl + p` for Windows and `cmd + p` for Mac) as a web page. Be sure to save them in the `input_path` folder you specify in the 'User settings' below.

Once completed, go to _Run > Run All Cells_ in this Jupyter Notebook and an output HTML file should be saved in the `output_path` folder you specify below.

## User settings

Change the settings below to affect the outputs from the tool:

In [186]:
# The path to the data you exported from Football Manager
export_path = "/Users/Oli/Code/Python/PyScoutFM/input/"

# The path to save the output from the tool to
output_path = "/Users/Oli/Code/Python/PyScoutFM/output/"

# The columns to specify in the output file
# Note: Any calculated columns will be appended automatically
output_columns = [
    'Name',
    'Age',
    'Club',
    'Transfer Value',
    'Wage',
    '1st Nat',
    'Position',
    'Personality',
    'Left Foot',
    'Right Foot',
]

# The attribute weighting set to use
weightings_to_use = 'ykykykyky'

# Filter out attributes that are below a certain value
# Note: Set this to 0 if you don't want to filter out any
filter_values_below = 50

# How many players to show on each page of the output file?
paginate = 25

## Attribute weightings

We define attribute weightings in this section.

When the weightings are multiplied by a player's attributes, a percentage score is generated for how effective that player is, out of 100. The weightings can be constrained by specific positions, preventing Midfielders being given a score in the Striker column for example.

We use a Python dictionary to hold the attribute weightings with the following data structure:

```python
weightings = {
    # Specify the name of your own weighting set or use the existing ones
    'my_custom_weighting_set': {
        # In this example we've specified 'iwb' (inverted wingback) as the key
        'iwb': {
            'positions': {
                # List the relevant positions here. For example:
                'WB',
                'D (LC)',
            },
            'weights': {
                # List the player's attributes and corresponding weight, out of 100. For example:
                'Cor': 5,
                'Cro': 1,
                'Dri': 40,
                # ...
                'Sta': 30,
                'Str': 50,
            
                # You can even specify the importance of using both feet
                'Feet': 25
            }
        }
    }
}
```

By default, the values from [ykykykyky's work](https://fm-arena.com/find-comment/10974/) are used in this tool. Please note that these were derived by testing a specific tactic. As such, consider whether they fit in with your current tactics and/or desired playing style and adjust accordingly.

### Weightings

In [187]:
weightings = {
    'ykykykyky': {
        'gk': {
            'positions': { 'GK' },
            'weights': {
                # Technical
                'Aer': 60, 'Cmd': 40, 'Com': 30, 'Ecc': 20, 'Fir': 30, 'Han': 50, 'Kic': 35, '1v1': 45, 'Pas': 45, 'Pun': 0, 'Ref': 80, 'TRO': 40,'Thr': 30,
                # Mental
                'Agg': 40,'Ant': 40,'Bra': 30, 'Cmp': 40, 'Cnt': 65, 'Dec': 50, 'Det': 20, 'Fla': 20, 'Ldr': 10, 'OtB': 0, 'Pos': 40, 'Tea': 10, 'Vis': 40, 'Wor': 10,
                # Physical
                'Acc': 70, 'Agi': 100, 'Bal': 20, 'Jum': 45, 'Nat': 10, 'Pac': 50, 'Sta': 10, 'Str': 70,
                # Other
                'Feet': 10
            }
        },
        'cd': {
            'positions': { 'D '},
            'weights': {
                # Technical
                'Cor': 5, 'Cro': 1, 'Dri': 40, 'Fin': 10, 'Fir': 35, 'Fre': 10, 'Hea': 55, 'Lon': 10, 'L Th': 5, 'Mar': 55, 'Pas': 55, 'Pen': 10, 'Tck': 40, 'Tec': 35,
                # Mental
                'Agg': 40, 'Ant': 50, 'Bra': 30, 'Cmp': 80, 'Cnt': 50, 'Dec': 50, 'Det': 20, 'Fla': 10, 'Ldr': 10, 'OtB': 10, 'Pos': 55, 'Tea': 10, 'Vis': 50, 'Wor': 55,
                # Physical
                'Acc': 90, 'Agi': 60, 'Bal': 35, 'Jum': 65, 'Nat': 10, 'Pac': 90, 'Sta': 30, 'Str': 50,
                # Other
                'Feet': 25
            }
        },
        'fb': {
            'positions': { 
                'WB', 'D (LC)', 'D (RC)', 'D (RLC)', 'D (RL)', 'D (L)', 'D (R)'
            },
            'weights': {
                # Technical
                'Cor': 30, 'Cro': 25, 'Dri': 50, 'Fin': 10, 'Fir': 30, 'Fre': 10, 'Hea': 20, 'Lon': 10, 'L Th': 30, 'Mar': 45, 'Pas': 45, 'Pen': 10, 'Tck': 50, 'Tec': 45,
                # Mental
                'Agg': 45, 'Ant': 45, 'Bra': 20, 'Cmp': 30, 'Cnt': 45, 'Dec': 45, 'Det': 20, 'Fla': 20, 'Ldr': 10, 'OtB': 70, 'Pos': 30, 'Tea': 10, 'Vis': 25, 'Wor': 90,
                # Physical
                'Acc': 100, 'Agi': 60, 'Bal': 25, 'Jum': 40, 'Nat': 10, 'Pac': 90, 'Sta': 100, 'Str': 25,
                # Other
                'Feet': 20
            }
        },
        'dm': {
            'positions': { 'DM' },
            'weights': {
                # Technical
                'Cor': 10, 'Cro': 10, 'Dri': 45, 'Fin': 20, 'Fir': 50, 'Fre': 30, 'Hea': 10, 'Lon': 40, 'L Th': 5, 'Mar': 20, 'Pas': 65, 'Pen': 10, 'Tck': 35, 'Tec': 50,
                # Mental
                'Agg': 50, 'Ant': 55, 'Bra': 30, 'Cmp': 60, 'Cnt': 50, 'Dec': 65, 'Det': 20, 'Fla': 50, 'Ldr': 10, 'OtB': 40, 'Pos': 65, 'Tea': 10, 'Vis': 55, 'Wor': 90,
                # Physical
                'Acc': 65, 'Agi': 45, 'Bal': 35, 'Jum': 15, 'Nat': 10, 'Pac': 70, 'Sta': 70, 'Str': 35,
                # Other
                'Feet': 50
            }
        },
        'w': {
            'positions': {
                'AM (L)', 'AM (LC)', 'AM (R)', 'AM (RC)', 'AM (RL)', 'AM (RLC)', 'M (R)', 'M (RC)', 'M (RL)', 'M (RLC)', 'M (L)', 'M (LC)',
            },
            'weights': {
                # Technical
                'Cor': 30, 'Cro': 65, 'Dri': 55, 'Fin': 15, 'Fir': 30, 'Fre': 10, 'Hea': 10, 'Lon': 10, 'L Th': 30, 'Mar': 35, 'Pas': 50, 'Pen': 15, 'Tck': 35, 'Tec': 50,
                # Mental
                'Agg': 34, 'Ant': 45, 'Bra': 15, 'Cmp': 30, 'Cnt': 35, 'Dec': 35, 'Det': 20, 'Fla': 20, 'Ldr': 10, 'OtB': 40, 'Pos': 35, 'Tea': 10, 'Vis': 35, 'Wor': 75,
                # Physical
                'Acc': 100, 'Agi': 50, 'Bal': 15, 'Jum': 10, 'Nat': 10, 'Pac': 100, 'Sta': 75, 'Str': 30,
                # Other
                'Feet': 20
            }
        },
        'amc': {
            'positions': {
                'M (C)', 'M (RC)', 'M (RLC)', 'M (LC)', 'AM (C)', 'AM (RC)', 'AM (RLC)', 'AM (LC)'
            },
            'weights': {
                # Technical
                'Cor': 5, 'Cro': 5, 'Dri': 65, 'Fin': 65, 'Fir': 40, 'Fre': 30, 'Hea': 10, 'Lon': 20, 'L Th': 1, 'Mar': 5, 'Pas': 50, 'Pen': 15, 'Tck': 15, 'Tec': 65,
                # Mental
                'Agg': 50, 'Ant': 70, 'Bra': 20, 'Cmp': 35, 'Cnt': 25, 'Dec': 40, 'Det': 20, 'Fla': 20, 'Ldr': 10, 'OtB': 35, 'Pos': 10, 'Tea': 10, 'Vis': 30, 'Wor': 80,
                # Physical
                'Acc': 100, 'Agi': 30, 'Bal': 50, 'Jum': 10, 'Nat': 10, 'Pac': 80, 'Sta': 80, 'Str': 30,
                # Other
                'Feet': 20
            }
        },
        'st': {
            'positions': { 
                'ST' 
            },
            'weights': {
                # Technical
                'Cor': 5, 'Cro': 5, 'Dri': 75, 'Fin': 80, 'Fir': 50, 'Fre': 5, 'Hea': 25, 'Lon': 25, 'L Th': 1, 'Mar': 1, 'Pas': 40, 'Pen': 20, 'Tck': 5, 'Tec': 65,
                # Mental
                'Agg': 50, 'Ant': 50, 'Bra': 20, 'Cmp': 35, 'Cnt': 5, 'Dec': 45, 'Det': 20, 'Fla': 25, 'Ldr': 10, 'OtB': 45, 'Pos': 5, 'Tea': 10, 'Vis': 20, 'Wor': 60,
                # Physical
                'Acc': 100, 'Agi': 30, 'Bal': 50, 'Jum': 20, 'Nat': 10, 'Pac': 70, 'Sta': 65, 'Str': 25,
                # Other
                'Feet': 20
            }
        }
    }
}

feet = {
    "Very Strong": 10,
    "Strong": 8,
    "Fairly Strong": 6,
    "Reasonable": 4,
    "Weak": 2,
    "Very Weak": 0,
}

## The engine

### Import the data

In [188]:
import pandas as pd

import glob
import os

In [189]:
# Get the most recent HTML file from the export path
files = glob.glob(os.path.join(export_path, '*.html'))
latest_file = max(files, key=os.path.getctime)

print(latest_file)

/Users/Oli/Code/Python/PyScoutFM/input/Player Search.html

In [190]:
# Turn the FM data into a dataframe
fm_export = pd.read_html(latest_file, header=0, encoding="UTF-8", keep_default_na=False)
fm_export = fm_export[0]

# Fix the Nationality and Natural Fitness columns
fm_export = fm_export.rename(columns={
    'Nat': '1st Nat',
    'Nat.1': 'Nat'
})

# Calculate feet scores
fm_export['Lft'] = fm_export['Left Foot'].map(feet)
fm_export['Rft'] = fm_export['Right Foot'].map(feet)
fm_export['Feet'] = fm_export['Lft'] + fm_export['Rft']

### Calculate Player ratings

To calculate player ratings, we take the attribute weightings and multiply them by the output from Football Manager.

In [191]:
def calculate_position_score(df, role_key, role_data):
    df_role = df.copy()

    # Filter the dataframe for eligible players eligible based on their position
    positions = role_data['positions']
    eligible_players = df_role['Position'].apply(lambda x: any(pos in x for pos in positions))
    
    # Filter and convert the weightings to a decimal
    att_weightings = {k: v / 100 for k, v in role_data['weights'].items() if v >= filter_values_below}

    theoretical_max_score = sum(value for value in att_weightings.values()) * 20

    df_role[role_key.upper()] = 0.0

    for attr, scale in att_weightings.items():
        if attr in df_role.columns:
            # Get explicit with types to prevent warnings in Pandas
            df_role[attr] = df_role[attr].astype(float)
            
            # Calculate the attribute weightings
            df_role.loc[eligible_players, attr] = pd.to_numeric(df_role.loc[eligible_players, attr], errors='coerce') * scale

    # Convert the attribute weightings to a percentage
    df_role.loc[eligible_players, role_key.upper()] = df_role.loc[eligible_players, att_weightings.keys()].sum(axis=1) / theoretical_max_score * 100

    return df_role[role_key.upper()].round(2).astype(float)

for role_key, role_data in weightings[weightings_to_use].items():
    fm_export[role_key.upper()] = calculate_position_score(fm_export, role_key, role_data)

fm_export

,Inf,Name,Age,Wage,Transfer Value,1st Nat,2nd Nat,Position,Club,Min AP,...,Lft,Rft,Feet,GK,CD,FB,DM,W,AMC,ST
0,,Tomás Aballay,23,"£1,200 p/w",£60K - £600K,ARG,,M/AM (L),Unión (SF),-,...,10,2,12,0.0,0.0,0.0,0.00,59.92,0.00,0.00
1,,Ahmed Abdelkader,27,"£29,500 p/w",£3.9M - £5.8M,EGY,,"AM (LC), ST (C)",Al-Ahly,-,...,6,10,16,0.0,0.0,0.0,0.00,64.92,64.37,65.17
2,Ctr,Luciano Aberasteguy,23,£120 p/w,£28K - £80K,URU,,"AM (R), ST (C)",Deportivo Maldonado,-,...,4,10,14,0.0,0.0,0.0,0.00,58.06,0.00,56.12
3,,Roberto Abreu,27,"£1,200 p/w",£75K - £230K,ESP,,"DM, M (C)",Pulpileño,-,...,4,10,14,0.0,0.0,0.0,53.33,0.00,47.88,0.00
4,,Dilan Acevedo,23,£180 p/w,£30K - £325K,CHI,,M (C),U. de Concepción,-,...,4,10,14,0.0,0.0,0.0,0.00,0.00,54.64,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1087,,Franco Zapiola,25,"£34,000 p/w",£4.9M - £8.4M,ARG,,"M (L), AM (LC)",Estudiantes (LP),£4.5M,...,10,2,12,0.0,0.0,0.0,0.00,68.31,63.21,0.00
1088,Loa,Emil Zeil,20,"£1,800 p/w",£30K - £300K,GER,,M (C),Dynamo Dresden,£29.5K,...,4,10,14,0.0,0.0,0.0,0.00,0.00,53.41,0.00
1089,,Matías Zepeda,22,£250 p/w,£55K - £550K,CHI,,"DM, M (C)",Coquimbo,-,...,4,10,14,0.0,0.0,0.0,55.10,0.00,54.50,0.00
1090,Inj,Piero Zevallos,25,"£1,900 p/w",£35K - £350K,PER,,"DM, M (C)",Universidad San Martín,-,...,4,10,14,0.0,0.0,0.0,60.29,0.00,53.38,0.00
1091,,Tim Mathis Zimmermann,20,£750 p/w,£50K - £150K,GER,,M/AM (C),SV Waldhof Mannheim,-,...,4,10,14,0.0,0.0,0.0,0.00,0.00,48.54,0.00

### Form the output columns

In [192]:
# TODO: Have a 'best rating' column and 'best position' column

# Check that the columns exist
fm_output = fm_export[[col for col in output_columns if col in fm_export.columns]]

# Warn the user if a column cannot be found
for col in output_columns:
    if col not in fm_export.columns:
        print(f"Column '{col}' does not exist.")

for role_key, role_data in weightings[weightings_to_use].items():
    score_column = calculate_position_score(fm_export, role_key, role_data)
    
    # Append the calculate columns to the output
    fm_output = fm_output.join(score_column.to_frame())

### Generate the HTML output

In [193]:
# Taken from here: https://www.thepythoncode.com/article/convert-pandas-dataframe-to-html-table-python
# Creates a function to make a sortable html export

def generate_html(dataframe: pd.DataFrame):
    table = dataframe.to_html(table_id="fm_data", index=False, classes="display nowrap")
    
    html = f"""
    <html>
        <head>
            <meta charset="UTF-8">
            <title>PyScoutFM</title>
            <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
            <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
            <style>
                body {{
                    font-family: 'Roboto', sans-serif;
                }}
                #fm_data, #fm_data th, #fm_data td {{
                    border: none !important;
                }}
            </style>
        </head>
        <body>
            <h1>PyScoutFM - Output</h1>
            <div>
            {table}
            </div>
            <script type="text/javascript" src="https://code.jquery.com/jquery-3.7.1.slim.min.js" integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
            <script type="text/javascript" src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>
            <script type="text/javascript">
                new DataTable('#fm_data', {{
                    pageLength: {paginate}
                }});
            </script>
        </body>
    </html>
    """
    
    return html

In [194]:
from datetime import datetime

# Generate the filename using datetime stamps (makes it easier to get the latest file this way!)
filename = str(datetime.now().strftime("%Y%m%d_%H%M%S")) + ".html"

# Create the output directory path
if not os.path.exists(output_path):
    os.makedirs(output_path)

# Write the HTML to disk
html = generate_html(fm_output)
open(output_path + filename, "w", encoding="UTF-8").write(html)

filename = (output_path + filename)
print(filename)

/Users/Oli/Code/Python/PyScoutFM/output/20231031_130709.html